spring.application.name=att_pontuada

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_api_att_pontuada
spring.datasource.username=root
spring.datasource.password=